language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2" Temporary disabling Python3
install:
  - pip install .
  - pip install beaker --use-mirrors
  - pip install Bottle --use-mirrors
  - pip install GitPython --use-mirrors
  - pip install bottle-cork --use-mirrors
  - pip install setproctitle --use-mirrors
  - pip install webtest --use-mirrors

script: 
  - nosetests
